"""AI-OS Documentation Engine - Generates and retrieves system docs."""
import time
from datetime import datetime, timezone


class DocumentationEngine:
    def __init__(self, state_registry=None):
        self._state = state_registry
        self._doc_store = {}
        self._tick_count = 0
        self._last_tick = None
        self._auto_topics = [
            "system_overview", "layer_map", "api_reference",
            "security_guide", "operator_manual", "troubleshooting",
        ]
        self._bootstrap_docs()

    def _bootstrap_docs(self) -> None:
        for topic in self._auto_topics:
            if topic not in self._doc_store:
                self._doc_store[topic] = self._generate_content(topic)

    def _generate_content(self, topic: str) -> dict:
        templates = {
            "system_overview": "AI-OS v2.0-CC2 is a 7-layer autonomous operating system. "
                               "It runs on virtual hardware abstracted from the host, managed by operator Chris.",
            "layer_map": "Layer 1: Physical Abstraction | Layer 2: Virtual Hardware | "
                         "Layer 3: Kernel Bridge | Layer 4: Process & Memory | "
                         "Layer 5: Engine & Intelligence | Layer 6: Command & Interface | "
                         "Layer 7: Application & Output",
            "api_reference": "GET /api/status - Returns full system status JSON. "
                             "Responses include all subsystem health, uptime, and metrics.",
            "security_guide": "All access is gated by PolicyEngine. Identity enforced via identity.lock. "
                              "Operator: Chris. Level: OPERATOR_ONLY for privileged operations.",
            "operator_manual": "Boot: python main.py --ui terminal. "
                               "Commands available via CommandCenter menu (1-16). "
                               "Shutdown requires operator token.",
            "troubleshooting": "Check logs/ directory for errors. "
                               "Run Diagnostic menu option 11 for system health report. "
                               "RepairEngine auto-scans every 5 ticks.",
        }
        return {
            "topic": topic,
            "content": templates.get(topic, f"Documentation for {topic} - auto-generated by DocumentationEngine."),
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "version": "2.0.0-CC2",
        }

    def tick(self) -> None:
        self._tick_count += 1
        self._last_tick = time.time()
        if self._tick_count % 20 == 0:
            self._refresh_docs()

    def _refresh_docs(self) -> None:
        for topic in self._auto_topics:
            doc = self._doc_store.get(topic, {})
            doc["last_verified"] = datetime.now(timezone.utc).isoformat()
            self._doc_store[topic] = doc

    def generate(self, topic: str) -> dict:
        doc = self._generate_content(topic)
        self._doc_store[topic] = doc
        if self._state:
            self._state.set(f"doc:{topic}", doc, namespace="docs")
        return doc

    def retrieve(self, topic: str) -> dict:
        if topic in self._doc_store:
            return self._doc_store[topic]
        return self.generate(topic)

    def list_topics(self) -> list:
        return list(self._doc_store.keys())

    def status(self) -> dict:
        return {
            "component": "DocumentationEngine",
            "tick_count": self._tick_count,
            "doc_count": len(self._doc_store),
            "topics": list(self._doc_store.keys()),
            "last_tick": self._last_tick,
            "healthy": True,
        }
